package RandomScripts;
// Develop and test a program to enter a maximum of five lines of text through keyboard terminating each line by a period operator. 
// The number of lines of text to be entered should be generated by a random number generator. 
// Remove the period symbol from each line and count the number of words in it excluding the articles and prepositions. 
// The number of articles and preposition present in the lines should also be counted and the number of words, articles and prepositions 
// should be displayed in the form of three different tables each showing the word/article/preposition and its frequency in the entire text lines. 
// Count the number of characters in the text entered. Convert each word except the articles and the prepositions into title case and display the entire text.

import java.util.Scanner;

public class LineProperties {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int n = (int) (Math.random() * 5) + 1;
        String[] str = new String[n];
        for (int i = 0; i < n; i++) {
            System.out.print("Enter the " + (i + 1) + " line of text: ");
            str[i] = sc.nextLine();
        }
        System.out.println();
        System.out.println("The number of lines of text entered is " + n);
        System.out.println();
        System.out.println("The number of words excluding the articles and prepositions is " + countWords(str));
        System.out.println();
        System.out.println("The number of articles and prepositions is " + countArticlesAndPrepositions(str));
        System.out.println();
        System.out.println("The number of characters in the text entered is " + countCharacters(str));
        System.out.println();
        System.out.println("The text entered in title case is: ");
        titleCase(str);
        displayTitleCase(str);
        sc.close();

    }

    public static int countWords(String[] str) {
        int count = 0;
        for (int i = 0; i < str.length; i++) {
            String[] words = str[i].split(" ");
            for (int j = 0; j < words.length; j++) {
                if (!words[j].equals("a") && !words[j].equals("an") && !words[j].equals("the") && !words[j].equals("of")
                        && !words[j].equals("and") && !words[j].equals("or") && !words[j].equals("for")
                        && !words[j].equals("in") && !words[j].equals("is") && !words[j].equals("are")) {
                    count++;
                }
            }
        }
        return count;
    }

    public static int countArticlesAndPrepositions(String[] str) {
        int count = 0;
        for (int i = 0; i < str.length; i++) {
            String[] words = str[i].split(" ");
            for (int j = 0; j < words.length; j++) {
                if (words[j].equals("a") || words[j].equals("an") || words[j].equals("the") || words[j].equals("of")
                        || words[j].equals("and") || words[j].equals("or") || words[j].equals("for")
                        || words[j].equals("in") || words[j].equals("is") || words[j].equals("are")) {
                    count++;
                }
            }
        }
        return count;
    }

    public static int countCharacters(String[] str) {
        int count = 0;
        for (int i = 0; i < str.length; i++) {
            count += str[i].length();
        }
        return count;
    }

    public static void titleCase(String[] str) {
        for (int i = 0; i < str.length; i++) {
            String[] words = str[i].split(" ");
            for (int j = 0; j < words.length; j++) {
                if (!words[j].equals("a") && !words[j].equals("an") && !words[j].equals("the") && !words[j].equals("of")
                        && !words[j].equals("and") && !words[j].equals("or") && !words[j].equals("for")
                        && !words[j].equals("in") && !words[j].equals("is") && !words[j].equals("are")) {
                    words[j] = words[j].substring(0, 1).toUpperCase() + words[j].substring(1);
                }
            }
            str[i] = String.join(" ", words);
        }
    }

    public static void displayTitleCase(String[] str) {
        for (int i = 0; i < str.length; i++) {
            System.out.println(str[i]);
        }
    }

}